In [1]:
import tensorflow as tf

from tensorflow.python.framework.ops import EagerTensor
print("Eager Execution Enabled:", tf.executing_eagerly())
print("Available Devices:")
for device in tf.config.list_physical_devices():
    print(device)

tf.debugging.set_log_device_placement(False)

Eager Execution Enabled: True
Available Devices:
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [2]:
%load_ext tensorboard


In [3]:
a = tf.constant(1)
print(a.shape)


()


2024-12-29 23:09:19.737726: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2024-12-29 23:09:19.737750: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-12-29 23:09:19.737756: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-12-29 23:09:19.737769: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-12-29 23:09:19.737778: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
b = tf.constant([1,2,3,4,5])
print(b.shape)


(5,)


In [5]:
import tensorflow as tf

a = tf.constant([1, 2, 3, 4, 5])
first_three_elem = a[:3]
fourth_elem = a[3]

# Directly convert to NumPy or Python objects with .numpy()
print(first_three_elem.numpy())  # [1 2 3]
print(fourth_elem.numpy()) 


[1 2 3]
4


In [6]:
a = tf.constant([1.0, 1.1, 2.1, 3.1], dtype=tf.float32, name='a_const')
print(a)

tf.Tensor([1.  1.1 2.1 3.1], shape=(4,), dtype=float32)


In [7]:
import tensorflow as tf

# Instead of using a placeholder + session.run, define everything as tensors:
a = tf.constant([[0.1, 0.2, 0.3]], dtype=tf.float32)
b = tf.constant([[10, 10, 10]], dtype=tf.float32)

# Perform your operation directly
c = a + b

In [8]:
print(c)

tf.Tensor([[10.1 10.2 10.3]], shape=(1, 3), dtype=float32)


In [9]:
import numpy as np
# In TF 2.x, we don't use placeholders or sessions; instead, we define tensors and operate on them directly.

# We'll simulate your input shape (None, 3) by creating two tf.constant tensors from Python lists or NumPy arrays.
# 'None' in the first dimension simply means it can be any batch size.

a_vals_1 = [[0.1,0.2,0.3]]
b_vals_1 = [[10,10,10]]

# Create TF tensors
a_1 = tf.constant(a_vals_1, dtype=tf.float32)
b_1 = tf.constant(b_vals_1, dtype=tf.float32)

# Add the tensors
c_1 = a_1 + b_1
print(c_1.numpy())  # [[10.1 10.2 10.3]]

# For the multi-row example
v_a = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
v_b = np.array([[6,5,4],[3,2,1]], dtype=np.float32)

a_2 = tf.constant(v_a, dtype=tf.float32)
b_2 = tf.constant(v_b, dtype=tf.float32)

c_2 = a_2 + b_2
print(c_2.numpy()) 

[[10.1 10.2 10.3]]
[[7. 7. 7.]
 [7. 7. 7.]]


In [10]:
import tensorflow as tf
import numpy as np

# Variable initialized randomly
var = tf.Variable(
    tf.random.normal([1, 3]),
    name="first_variable",
    dtype=tf.float32
)

# Variable initialized with constant values
init_val = np.array([4, 5])
var2 = tf.Variable(
    init_val.reshape([1, 2]),
    name="second_variable",
    dtype=tf.int32
)

# In TF 2.x, no session or global init call is needed.
print(var.numpy())
print(var2.numpy())

[[ 1.1468321 -1.8221927  1.7510278]]
[[4 5]]


In [11]:
var2 = tf.Variable(
    tf.zeros([1, 2], dtype=tf.int32),
    name="variable",
    trainable=False
)

In [12]:
import tensorflow as tf
import numpy as np

# Equivalent to tf.constant(3.0, name='constant1')
const1 = tf.constant(3.0, name='constant1')

# Equivalent to tf.get_variable("variable1", shape=[1,2], dtype=tf.float32)
var = tf.Variable(
    tf.random.normal([1,2]),
    name="variable1",
    dtype=tf.float32
)

# Equivalent to tf.get_variable("variable2", shape=[1,2], trainable=False, dtype=tf.float32)
var2 = tf.Variable(
    tf.random.normal([1,2]),
    name="variable2",
    dtype=tf.float32,
    trainable=False
)

# These ops are directly computed in eager mode:
op1 = const1 * var
op2 = op1 + var2
op3 = tf.reduce_mean(op2)

# Print results immediately (no Session needed)
print(op3.numpy())

-1.2997332


In [13]:
logdir = "logs/graph_demo"
writer = tf.summary.create_file_writer(logdir)

# Actually record the trace
with writer.as_default():
    tf.summary.trace_on(graph=True, profiler=False)
    tf.summary.trace_export(name="my_graph", step=0)

In [14]:
%tensorboard --logdir logs/graph_demo


Reusing TensorBoard on port 6006 (pid 85848), started 2:35:02 ago. (Use '!kill 85848' to kill it.)

In [25]:
with tf.device('/GPU:0'):  # Explicitly use Metal GPU
    a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
    b = tf.constant([[1.0, 1.0], [0.0, 1.0]])
    c = tf.matmul(a, b)
    print(c)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
